version: "3.8"

services:
    danceagent:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80"
        labels:
            - "traefik.http.services.danceagent.loadbalancer.server.port=80"
            - "traefik.http.routers.danceagent.rule=PathPrefix(`/danceagent`)"
            - "traefik.http.routers.danceagent.middlewares=danceagent-stripprefix" 
            - "traefik.http.middlewares.danceagent-stripprefix.stripprefix.prefixes=/danceagent"
        networks:
            - traefik_default

networks:
  traefik_default:
    external: true
    